### ISSUE TITLE
A tagged release

### ISSUE THREAD

**Issue by tisaac** [fospald/fibergen#1]
Hi @fospald,

One of my checkboxes in the JOSS review (openjournals/joss-reviews#1027) asks whether the version we're reviewing matches the "github release".  fibergen doesn't currently have any releases.  I'm not sure whether a release version is mandatory or not (EDIT: editor has indicated it is not), but either way I would recommend that you start tagging releases.  Numbered releases help in distribution (if you're thinking of packaging fibergen), and they help users keep track of which version they can use (you may make changes down the line that introduce incompatibilities).

Since you're starting fresh, I'd suggest you consider the [semantic versioning](semver.org) convention.

**Comment by fospald** [comment]
Hi @tisaac,
I will make only small changes in the future and try to keep things compatible. As this is not a library for developers, but a tool I use the new ISO versioning currently 2018.1. But I will create a release once we have finished the reviewing process.

**Comment by tisaac** [comment]
Good point about being a tool rather than a library.
