### ISSUE TITLE
boost/detail/endian.hpp not available in recent boost versions

### ISSUE THREAD

**Issue by michpaulatto** [fospald/fibergen#10]
Hi,
I've run across an issue when installing fibergen with boost 1.73.0. I am installing on a MacBook Air with Python 3.8.
Problem: The file boost/detail/endian.hpp is no longer available in version 1.73.0 of Boost. fibergen.cpp includes the file at line 128. Compilation fails with message:
`fatal error: 
      'boost/detail/endian.hpp' file not found
#include <boost/detail/endian.hpp>`
This doesn't seem to be a problem on another Mac with the same version of Boost and Python.
Possible solution: in fibergen/src/fibergen.cpp at line 128 replace:
`#include <boost/detail/endian.hpp>`
with
 `#include <boost/predef/other/endian.h>`

Best
Michele
PS, I am a complete noob in regards to cpp and boost so I may be wrong

**Comment by fospald** [comment]
I also replaced it in the source. Thank you!
