### ISSUE TITLE
I could not install boost-numeric-bindings

### ISSUE THREAD

**Issue by Fengyixin-research** [fospald/fibergen#11]
I have followed this instruction in [https://mathema.tician.de/software/boost-numeric-bindings/], however, the configure file seems not right for it is an old version.

```
Traceback (most recent call last):
  File "./configure", line 62, in <module>
    file(fname, "w").write("".join(new_lines))
NameError: name 'file' is not defined
```
Would you mind showing the solutions? I will owe my gratitude.

**Comment by fospald** [comment]
I think you need to run the configure script with python2. You need only the headers for boost-numeric-bindings the Makefile will only copy the headers to the target directory.
