### ISSUE TITLE
Unable to install: developer local files

### ISSUE THREAD

**Issue by tisaac** [fospald/fibergen#2]
https://github.com/fospald/fibergen/blob/207d07d6ae7d7d2ff4d86729ade48b8b26ff77cf/build.sh#L6

Users should not have to modify hard-coded paths in a build script.

At a minimum, please:
- Make the build script depend on environment variables for the locations of dependencies
- Be complete and specific (version numbers) in describing dependencies in installation instructions

For something more sustainable, please consider a flexible [compiling and configuration tool](https://en.wikipedia.org/wiki/Category:Compiling_tools) to help make this project portable.

(Issue raised as part of JOSS review openjournals/joss-reviews#1027)

**Comment by fospald** [comment]
Sorry, I forgot to remove these lines. But it should also work, if the files are not found. The build script uses cmake. Is there any other error message?
Do you mean I should make build.sh portable, e.g. only use cmake without build.sh?
The version requirements are Python 3 and Qt 5, for the other libraries there are no restrictions (it should work with the latest version, but also older versions)

**Comment by tisaac** [comment]
Oh, I didn't see that after `build.sh` everything is cmake based.  My mistake, you can ignore my suggestion about configuration tools.

On the other hand, `build.sh` isn't currently parameterized: there's no way to pass arguments to the cmake invocation.  CMake is common enough: maybe you should recommend users just use it directly, and take `build.sh` out of the repo?

You're also right that those lines didn't cause my configure errors.  You should probably still remove them and other references to `/LOCAL/` (Which also appears in `CMakeLists.txt`).

**Comment by fospald** [comment]
Hi, I have cleaned up the scripts. The build script is simple enough for editing. Now you can also pass CMake parameters as arguments to build.sh. Do you still have errors?

**Comment by tisaac** [comment]
The new bulid script works for me, thanks!
