### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by tisaac** [fospald/fibergen#4]
By my count there are three demos (elasticity/hashin, elasticity/laminate, viscosity/nunan_keller) where empirical or analytic values that can be compared against the output of the solver are stored as comments in the xml files.  It would be great if these tests could be turned into a `make test` target in CMake as automated tests.

(Issue opened as part of JOSS review openjournals/joss-reviews#1027

**Comment by fospald** [comment]
I have updated the test routines (need recompile). You can perform some tests using
fibergen --test
The demos are not suitable for testing, as the results depend on the resolution, solver method, etc. or are too simple (laminate) or values too inaccurate (nunan_keller) instead I check some central operations and operators.
