### ISSUE TITLE
Could NOT find OpenMP_C - Error on MacOS

### ISSUE THREAD

**Issue by ctdegroot** [fospald/fibergen#5]
Full error message:

CMake Error at /usr/local/Cellar/cmake/3.12.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.12.4/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.12.4/share/cmake/Modules/FindOpenMP.cmake:466 (find_package_handle_standard_args)
  CMakeLists.txt:49 (FIND_PACKAGE)

OpenMP is installed by Homebrew package manager.

**Comment by fospald** [comment]
I think the answer is here:
https://stackoverflow.com/questions/46414660/macos-cmake-and-openmp
Can you try this? Otherwise I will try to add something to CMakeLists.txt to make it work, but I do not have MacOS.

**Comment by ctdegroot** [comment]
Ok, I've pasted the following into CMakeLists.txt:

OPTION (USE_OpenMP "Use OpenMP to enamble <omp.h>" ON)

```
# Find OpenMP
if(APPLE AND USE_OpenMP)
    if(CMAKE_C_COMPILER_ID MATCHES "Clang")
        set(OpenMP_C "${CMAKE_C_COMPILER}")
        set(OpenMP_C_FLAGS "-fopenmp=libomp -Wno-unused-command-line-argument")
        set(OpenMP_C_LIB_NAMES "libomp" "libgomp" "libiomp5")
        set(OpenMP_libomp_LIBRARY ${OpenMP_C_LIB_NAMES})
        set(OpenMP_libgomp_LIBRARY ${OpenMP_C_LIB_NAMES})
        set(OpenMP_libiomp5_LIBRARY ${OpenMP_C_LIB_NAMES})
    endif()
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      set(OpenMP_CXX "${CMAKE_CXX_COMPILER}")
      set(OpenMP_CXX_FLAGS "-fopenmp=libomp -Wno-unused-command-line-argument")
      set(OpenMP_CXX_LIB_NAMES "libomp" "libgomp" "libiomp5")
      set(OpenMP_libomp_LIBRARY ${OpenMP_CXX_LIB_NAMES})
      set(OpenMP_libgomp_LIBRARY ${OpenMP_CXX_LIB_NAMES})
      set(OpenMP_libiomp5_LIBRARY ${OpenMP_CXX_LIB_NAMES})
    endif()
endif()
```

It seems to get past the OpenMP part, but gets a boost error now. I'll have a look into that first.

**Comment by ctdegroot** [comment]
I am going to close this issue for now. The next issue is finding boost.python.

**Comment by fospald** [comment]
Ok thank you. I will add this to CMakeLists.txt. Also I possibly can make multithreading with OpenMP optional.

**Comment by fospald** [comment]
@ctdegroot the tool should now also work without OpenMP by setting USE_OPENMP to OFF
