### ISSUE TITLE
cgi.escape not supported in Python 3.8

### ISSUE THREAD

**Issue by michpaulatto** [fospald/fibergen#9]
Hello
I have installed fibergen on a MacBook pro with python 3.8. When selecting an example project in the gui it crashes with the error:
`AttributeError: module 'cgi' has no attribute 'escape'`
I have done some googling and apparently cgi.parse has been removed from python 3.8. I have solved the problem by adding the following import statement at the top of fibergen_gui.py:
`from html import escape`
And substituting every instance of `cgi.escape()` with `escape()`

Best
Michele

**Comment by fospald** [comment]
Thank you! I fixed it.
